name: freader
description: Your description

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <3.4.0"
  flutter: ">=3.16.0 <4.0.0"

dependency_overrides:
  xml: ^6.3.0
  meta: 1.9.0
  image: ^4.1.3
dependencies:
  archive: ^3.3.7
  background_downloader: ^6.0.1
  bloc_concurrency: ^0.2.1
  collection: ^1.17.0
  drift: ^2.5.0
  # epubx: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_html: 3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^6.0.2
  flutter_sharing_intent: ^1.0.6
  flutter_widget_from_html: ^0.10.0
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  http: ^0.13.5
  auto_hyphenating_text: ^0.2.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  l: 3.2.0
  path: ^1.8.2
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  platform_info: ^3.2.0
  pure: 0.2.0
  rxdart: 0.27.7
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^7.1.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.17
  sizzle_lints: 1.0.10
  sqlite3_flutter_libs: ^0.5.13
  stack_trace: ^1.11.0
  stream_transform: ^2.1.0
  translator: ^0.1.7
  watcher: ^1.0.2
  webview_flutter: ^4.2.0
  xml: ^6.3.0
  # image: ^4.1.3
dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.1
  flutter_gen_runner: ^5.3.0
  # Utilities
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  # Codegen
  freezed: 2.3.2
  go_router_builder: any
  json_serializable: ^6.6.1 

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/books/

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 100
